### ISSUE TITLE
Investigate test fails

### ISSUE THREAD

**Issue by cdietrich** [itemis/xtext-reference-projects#166]
Tests seem no longer working on github action
we need to find out why

2021-03-10T17:17:29.0878059Z SWT SessionManagerDBus: Failed to connect to org.gnome.SessionManager: Failed to execute child process “dbus-launch” (No such file or directory)
2021-03-10T17:17:29.1013474Z SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Failed to execute child process “dbus-launch” (No such file or directory)

....

2021-03-10T17:09:49.7922207Z xtextProject_webIntegration_withLSPFatJar(org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest)  Time elapsed: 5.064 s  <<< ERROR!
2021-03-10T17:09:49.7925351Z org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find view matching: with id '"org.eclipse.ui.console.ConsoleView"'
2021-03-10T17:09:49.7928628Z 	at org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.tearDown(XtextNewProjectWizardTest.java:46)
2021-03-10T17:09:49.7932296Z Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find view matching: with id '"org.eclipse.ui.console.ConsoleView"'
2021-03-10T17:09:49.7935277Z 	at org.eclipse.xtext.swtbot.tests.XtextNewProjectWizardTest.tearDown(XtextNewProjectWizardTest.java:46)
2021-03-10T17:09:49.7936893Z

**Comment by cdietrich** [comment]
maybe new ubuntu default on github actions

**Comment by cdietrich** [comment]
using ubuntu 1804 helps :/

**Comment by cdietrich** [comment]
created https://github.com/actions/virtual-environments/issues/2896

**Comment by cdietrich** [comment]
dbus stuff is also there in 1804
=> different issue

**Comment by cdietrich** [comment]
in the screenshots i cannot see anything
https://github.com/itemis/xtext-reference-projects/actions/runs/640224655
see https://github.com/itemis/xtext-reference-projects/tree/cd_moreTstsx
for experiments

**Comment by cdietrich** [comment]
```
2021-03-10T18:30:44.9685383Z Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 5.373 s <<< FAILURE! - in org.eclipse.xtext.swtbot.tests.XtendExamplesTest
2021-03-10T18:30:44.9687803Z xtendSolutionsForEuler(org.eclipse.xtext.swtbot.tests.XtendExamplesTest)  Time elapsed: 2.006 s  <<< ERROR!
2021-03-10T18:30:44.9690133Z org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: The widget was null.
2021-03-10T18:30:44.9692513Z 	at org.eclipse.xtext.swtbot.tests.XtendExamplesTest.setUp(XtendExamplesTest.java:31)
``` also hints to missing junitView

**Comment by cdietrich** [comment]
will temorary use 18.04

**Comment by cdietrich** [comment]
problem can be reproduced on 20.04 when using Xvfb
