### ISSUE TITLE
Integration Tests do not fail if tests fail

### ISSUE THREAD

**Issue by ArneDeutsch** [itemis/xtext-reference-projects#36]
Observed in the log that some UI tests are failing but are reported to be successfull. Seems the build script does not recognize the failiure:

```
Results:
Failures: 
  XtextNewProjectWizardTest.xtextProject_forEclipse_withTesting:180 [Unsatisfied version constraint: 'org.junit.jupiter.api: [5.1.0,6.0.0)'
, Unsatisfied version constraint: 'org.junit.jupiter.api: [5.1.0,6.0.0)'
] expected:<0> but was:<2>
  XtextNewProjectWizardTest.xtextProject_forEclipse_withTesting_withGradle:246 [Unsatisfied version constraint: 'org.junit.jupiter.api: [5.1.0,6.0.0)'
, Unsatisfied version constraint: 'org.junit.jupiter.api: [5.1.0,6.0.0)'
] expected:<0> but was:<2>
  XtextNewProjectWizardTest.xtextProject_forEclipse_withTesting_withMaven:212 [Unsatisfied version constraint: 'org.junit.jupiter.api: [5.1.0,6.0.0)'
, Unsatisfied version constraint: 'org.junit.jupiter.api: [5.1.0,6.0.0)'
] expected:<0> but was:<2>
Tests run: 20, Failures: 3, Errors: 0, Skipped: 0
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Input Stream Closed
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:60)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Input Stream Closed
	at org.eclipse.ui.console.IOConsoleInputStream.available(IOConsoleInputStream.java:268)
	at org.eclipse.ui.console.IOConsoleInputStream.read(IOConsoleInputStream.java:95)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
	... 1 more
!ENTRY org.eclipse.core.resources 2 10035 2019-02-03 17:11:29.615
!MESSAGE The workspace will exit with unsaved changes in this session.
[ERROR] There are test failures.

[...]

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.eclipse.xtext.swtbot.parent .................... SUCCESS [  0.208 s]
[INFO] org.eclipse.xtext.integrationtests.target .......... SUCCESS [  0.256 s]
[INFO] org.eclipse.xtext.swtbot.testing ................... SUCCESS [  3.682 s]
[INFO] org.eclipse.xtext.swtbot.tests ..................... SUCCESS [31:34 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32:14 min
[INFO] Finished at: 2019-02-03T17:11:30Z
[INFO] Final Memory: 59M/583M
[INFO] ------------------------------------------------------------------------
The command "sh -e scripts/$BUILDCMD" exited with 0.

```

The build should fail instead.

**Comment by cdietrich** [comment]
@ArneDeutsch is it possible that old errors dont get removed.
the error looks not like it was the same for maven, gradle and tycho

**Comment by cdietrich** [comment]
@ArneDeutsch is JUnit 5 in the Target Platform?

**Comment by ArneDeutsch** [comment]
Build now fails is tests are failing. https://github.com/eclipse/xtext-core/pull/1014 should fix the failing but we will have to wait for the distro build beeing complete to be sure.
